package ru.nick252.types

import com.fasterxml.jackson.annotation.JsonAlias
import com.fasterxml.jackson.annotation.JsonProperty
import ru.nick252.types.server.Forecast

data class Attributes(
    val friendlyName: String?,
    val unitOfMeasurement: String?,
    val supportedFeatures: Int,
    val codeFormat: String?,
    val changedBy: String?,
    val codeArmRequired: String?,
    val prePendingState: String?,
    val postPendingState: String?,
    val nextDawn: String?,
    val nextDusk: String?,
    val deviceClass: String?,
    val temperature: Double?,
    val icon: String?,
    val lastTriggered: String?,
    val nextMidnight: String?,
    val currentPosition: Byte?,
    val batteryVoltage: Float?,
    val nextNoon: String?,
    val pressure: Float?,
    val windBearing: Float?,
    val windSpeed: Float?,
    val attribution: String?,
    val forecast: List<Forecast>?,
    val releaseNotes: String?,
    val nextSetting: String?,
    val editable: Boolean?,
    val id: String?,
    @JsonAlias("Latitude", "latitude") val latitude: Double?,
    @JsonAlias("Longitude", "longitude") val longitude: Double?,
    val gpsAccuracy: Long?,
    val source: String?,
    val entityPicture: String?,
    val userId: String?,
    val nextRising: String?,
    val elevation: Double?,
    val azimuth: Double?,
    val rising: Boolean?,
    val entity_id: List<String>?,
    val duration: String?,
    val radius: Double?,
    val passive: Boolean?,
    val isVolumeMuted: Boolean?,
    val sourceList: List<String>?,
    val volumeLevel: Double?,
    val activeChild: String?,
    val minMireds: Long?,
    val maxMireds: Long?,
    val effectList: List<String>?,
    val brightness: Long?,
    val colorTemp: Long?,
    val hsColor: List<Double>?,
    val rgbColor: List<Int>?,
    val xyColor: List<Double>?,
    val newestVersion: String?,
    val roundTripTimeAvg: Double?,
    val roundTripTimeMax: Double?,
    val roundTripTimeMdev: Double?,
    val roundTripTimeMin: Double?,
    val mode: String?,
    val current: Double?,
    val accessToken: String?,
    val sensorType: String?,
    val lastChanged: String?,
    val soundOutput: String?,
    val outletInUse: Boolean?,
    val hvacModes: List<String>?,
    val minTemp: Double?,
    val maxTemp: Double?,
    val targetTempStep: Double?,
    val currentTemperature: Double?,
    val hvacAction: String?,
    val isHidden: Boolean?,
    @param:JsonProperty("Administrative Area") val administrativeArea: String?,
    @param:JsonProperty("Sub Administrative Area") val subAdministrativeArea: String?,
    @param:JsonProperty("Country") val country: String?,
    @param:JsonProperty("ISO Country Code") val isoCountryCode: String?,
    @param:JsonProperty("Locality") val locality: String?,
    @param:JsonProperty("Postal Code") val postalCode: String?,
    @param:JsonProperty("Sub Locality") val subLocality: String?,
    @param:JsonProperty("Sub Thoroughfare") val subThoroughfare: String?,
    @param:JsonProperty("Thoroughfare") val thoroughfare: String?,
    @param:JsonProperty("Local Time") val localTime: String?,
    @param:JsonProperty("Package") val `package`: String?,
    @param:JsonProperty("Time in Milliseconds") val timeInMilliseconds: Long?,
    @param:JsonProperty("Free internal storage") val freeInternalStorage: String?,
    @param:JsonProperty("Total internal storage") val totalInternalStorage: String?,
    val inVehicle: Double?,
    val still: Double?,
    val unknown: Double?,
    val assumedState: Boolean,
    val currentPowerW: Double?,
    val manufacturer: String?,
    val model: String?,
    val swVersion: String?,
    val local: String?,
    val cloud: String?,
    val rssi: Double?,
    val power: Double?,
    val voltage: Double?,
    val repositories: List<Any>?,
    val soundModeList: List<String>?,
    val mediaContentType: String?,
    val mediaDuration: Double?,
    val mediaPosition: Double?,
    val mediaPositionUpdatedAt: String?,
    val mediaTitle: String?,
    val mediaArtist: String?,
    val soundMode: String?,
    val entityPictureLocal: String?,
    val aliceState: String?,
    val connectionClass: String?,
    val sourceType: String?,
    val altitude: Double?,
    val course: Double?,
    val speed: Double?,
    val verticalAccuracy: Double?,
    val restored: Boolean?,
    val title: String?,
    val message: String?
)